### ISSUE TITLE
Complement incorrectly doesn't match NUL (ascii 0) character.

### ISSUE THREAD

**Issue by RokLenarcic** [zhztheplayer/DFA-Regex#11]
`CommonSets.complementarySet` incorrectly processes `0` characters in array to always flip the bit for `\u0000`.

Example:
- `.` matches `\u0000` (ASCII `NUL`)
- `[^x]` doesn't match `\u0000` -> but it should, it matches every character except `x` and `\u0000`

**Comment by zhztheplayer** [comment]
Should be fixed in https://github.com/zhztheplayer/DFA-Regex/commit/5fd5690b59cdcb291e3f7a49a41a0ec49515fd76. Thanks for reporting, @RokLenarcic !

**Comment by zhztheplayer** [comment]
Closing. Feel free to reopen if issue still exists.

**Comment by RokLenarcic** [comment]
I have fixed this in a completely different way in my fork.

I have added function:

```
    public static char[] complementarySet(Set<Character> set) { // complementary set among ascii
        char[] ret = new char[ENCODING_LENGTH - set.size()];
        int i = 0;
        for (char c = 0; c < ENCODING_LENGTH; c++) {
            if (!set.contains(c)) {
                ret[i++] = c;
            }
        }
        return ret;
    }
```
And I changed `listToArray` to `collToArray` which allows sets to be used:
```
    public static char[] collToArray(Collection<Character> charList) {
        char[] result = new char[charList.size()];
        Iterator<Character> iter = charList.iterator();
        for (int i = 0; i < charList.size(); i++) {
            result[i] = iter.next();
        }
        return result;
    }
```

I changed `all` to be a set: `Set<Character> all = new HashSet<>();` and then the code in SyntaxTree becomes simply:

```
char[] chSet = isComplementarySet ?
                            CommonSets.complementarySet(all) :
                            CommonSets.collToArray(all);
```

**Comment by zhztheplayer** [comment]
Sorry for late reply, and thanks for sharing, @RokLenarcic .

I think your solution would be definitely working well. I agree that whether to use hashmaps or bitmaps doesn't really matter in the parsing phase.

And in future I may expect some refactoring of the engine to support large charsets like unicode within an efficient way. Maybe bitmaps will no longer be suitable at that time. So there would be a move.
