### ISSUE TITLE
Does it support grouping?

### ISSUE THREAD

**Issue by zhujiangang** [zhztheplayer/DFA-Regex#2]

**Comment by zhztheplayer** [comment]
Not yet.

It was proved to be possible to implement capture groups on a DFA engine. Although this is probably not something simple.

Be free to contribute if you have a plan to work on this on top of this project.

**Comment by zhujiangang** [comment]
Thanks. Is it easy to support NFA matching based on your code?

**Comment by zhztheplayer** [comment]
NFA matching has already been fully implemented by jvm native. So why do you want NFA to be covered by a DFA based engine?

If what you want is just implementing NFA-like features, such as capture groups, the answer will be "YES", and some papers might be useful, eg: [tagged dfa](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.29.4395&rep=rep1&type=pdf)
